version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/iris-client-fe"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/iris-client-fe"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker/nginx"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker/app-eps"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker/iris-client-eps"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/infrastructure/docker/iris-client-proxy"
    schedule:
      interval: "weekly"
      
