vars:
  EPS_OP:
    source: env
    variable: EPS_OP
    type: string
  EPS_CLIENT_CERT:
    source: env
    variable: EPS_CLIENT_CERT
    type: string
  EPS_CLIENT_CERT_KEY:
    source: env
    variable: EPS_CLIENT_CERT_KEY
    type: string        
  EPS_SD_ENDPOINT:
    source: env
    variable: EPS_SD_ENDPOINT
    type: string        
name: "$EPS_OP"
# IRIS Service directory. It provides information about IRIS participants such as connected Apps and locations of IRIS central services. 
directory:
  type: api
  settings:
    jsonrpc_client:
      tls:
        certificate_file: "$DIR/../../certs/$EPS_CLIENT_CERT"
        key_file: "$DIR/../../certs/$EPS_CLIENT_CERT_KEY"  
        ca_certificate_files: ["$DIR/../../certs/root.crt"]
    ca_certificate_files: ["$DIR/../../certs/root.crt"]
    endpoints: [ "$EPS_SD_ENDPOINT" ]
    server_names: [ "sd-1" ]
channels: # defines all the channels that we want to open when starting the server
  - name: Stdout channel
    type: stdout
    settings: { }
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://iris-client:8092/data-submission-rpc
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_files: ["$DIR/../../certs/root.crt"]
        certificate_file: "$DIR/../../certs/$EPS_CLIENT_CERT"
        key_file: "$DIR/../../certs/$EPS_CLIENT_CERT_KEY"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server
    settings:
      bind_address: "0.0.0.0:5556"
      tls:
        ca_certificate_files: ["$DIR/../../certs/root.crt"]
        certificate_file: "$DIR/../../certs/$EPS_CLIENT_CERT"
        key_file: "$DIR/../../certs/$EPS_CLIENT_CERT_KEY"
        verify_client: false
#signing:
#  certificate_file: "$DIR/../../certs/hd-1-sign.crt"
#  key_file: "$DIR/../../certs/hd-1-sign.key"
#  ca_certificate_file: "$DIR/../../certs/root.crt"
